export const COUNTRIES = [
  { label: "Afghanistan", value: "AF", callingCode: "+93", emoji: "🇦🇫" },
  { label: "Albania", value: "AL", callingCode: "+355", emoji: "🇦🇱" },
  { label: "Algeria", value: "DZ", callingCode: "+213", emoji: "🇩🇿" },
  { label: "Andorra", value: "AD", callingCode: "+376", emoji: "🇦🇩" },
  { label: "Angola", value: "AO", callingCode: "+244", emoji: "🇦🇴" },
  { label: "Argentina", value: "AR", callingCode: "+54", emoji: "🇦🇷" },
  { label: "Armenia", value: "AM", callingCode: "+374", emoji: "🇦🇲" },
  { label: "Australia", value: "AU", callingCode: "+61", emoji: "🇦🇺" },
  { label: "Austria", value: "AT", callingCode: "+43", emoji: "🇦🇹" },
  { label: "Azerbaijan", value: "AZ", callingCode: "+994", emoji: "🇦🇿" },
  { label: "Bahamas", value: "BS", callingCode: "+1-242", emoji: "🇧🇸" },
  { label: "Bahrain", value: "BH", callingCode: "+973", emoji: "🇧🇭" },
  { label: "Bangladesh", value: "BD", callingCode: "+880", emoji: "🇧🇩" },
  { label: "Barbados", value: "BB", callingCode: "+1-246", emoji: "🇧🇧" },
  { label: "Belarus", value: "BY", callingCode: "+375", emoji: "🇧🇾" },
  { label: "Belgium", value: "BE", callingCode: "+32", emoji: "🇧🇪" },
  { label: "Belize", value: "BZ", callingCode: "+501", emoji: "🇧🇿" },
  { label: "Benin", value: "BJ", callingCode: "+229", emoji: "🇧🇯" },
  { label: "Bhutan", value: "BT", callingCode: "+975", emoji: "🇧🇹" },
  { label: "Bolivia", value: "BO", callingCode: "+591", emoji: "🇧🇴" },
  { label: "Bosnia and Herzegovina", value: "BA", callingCode: "+387", emoji: "🇧🇦" },
  { label: "Botswana", value: "BW", callingCode: "+267", emoji: "🇧🇼" },
  { label: "Brazil", value: "BR", callingCode: "+55", emoji: "🇧🇷" },
  { label: "Brunei", value: "BN", callingCode: "+673", emoji: "🇧🇳" },
  { label: "Bulgaria", value: "BG", callingCode: "+359", emoji: "🇧🇬" },
  { label: "Burkina Faso", value: "BF", callingCode: "+226", emoji: "🇧🇫" },
  { label: "Burundi", value: "BI", callingCode: "+257", emoji: "🇧🇮" },
  { label: "Cabo Verde", value: "CV", callingCode: "+238", emoji: "🇨🇻" },
  { label: "Cambodia", value: "KH", callingCode: "+855", emoji: "🇰🇭" },
  { label: "Cameroon", value: "CM", callingCode: "+237", emoji: "🇨🇲" },
  { label: "Canada", value: "CA", callingCode: "+1", emoji: "🇨🇦" },
  { label: "Central African Republic", value: "CF", callingCode: "+236", emoji: "🇨🇫" },
  { label: "Chad", value: "TD", callingCode: "+235", emoji: "🇹🇩" },
  { label: "Chile", value: "CL", callingCode: "+56", emoji: "🇨🇱" },
  { label: "China", value: "CN", callingCode: "+86", emoji: "🇨🇳" },
  { label: "Colombia", value: "CO", callingCode: "+57", emoji: "🇨🇴" },
  { label: "Comoros", value: "KM", callingCode: "+269", emoji: "🇰🇲" },
  { label: "Congo, Democratic Republic of the", value: "CD", callingCode: "+243", emoji: "🇨🇩" },
  { label: "Congo, Republic of the", value: "CG", callingCode: "+242", emoji: "🇨🇬" },
  { label: "Costa Rica", value: "CR", callingCode: "+506", emoji: "🇨🇷" },
  { label: "Croatia", value: "HR", callingCode: "+385", emoji: "🇭🇷" },
  { label: "Cuba", value: "CU", callingCode: "+53", emoji: "🇨🇺" },
  { label: "Cyprus", value: "CY", callingCode: "+357", emoji: "🇨🇾" },
  { label: "Czech Republic", value: "CZ", callingCode: "+420", emoji: "🇨🇿" },
  { label: "Denmark", value: "DK", callingCode: "+45", emoji: "🇩🇰" },
  { label: "Djibouti", value: "DJ", callingCode: "+253", emoji: "🇩🇯" },
  { label: "Dominica", value: "DM", callingCode: "+1-767", emoji: "🇩🇲" },
  { label: "Dominican Republic", value: "DO", callingCode: "+1-809", emoji: "🇩🇴" },
  { label: "East Timor", value: "TL", callingCode: "+670", emoji: "🇹🇱" },
  { label: "Ecuador", value: "EC", callingCode: "+593", emoji: "🇪🇨" },
  { label: "Egypt", value: "EG", callingCode: "+20", emoji: "🇪🇬" },
  { label: "El Salvador", value: "SV", callingCode: "+503", emoji: "🇸🇻" },
  { label: "Equatorial Guinea", value: "GQ", callingCode: "+240", emoji: "🇬🇶" },
  { label: "Eritrea", value: "ER", callingCode: "+291", emoji: "🇪🇷" },
  { label: "Estonia", value: "EE", callingCode: "+372", emoji: "🇪🇪" },
  { label: "Eswatini", value: "SZ", callingCode: "+268", emoji: "🇸🇿" },
  { label: "Ethiopia", value: "ET", callingCode: "+251", emoji: "🇪🇹" },
  { label: "Fiji", value: "FJ", callingCode: "+679", emoji: "🇫🇯" },
  { label: "Finland", value: "FI", callingCode: "+358", emoji: "🇫🇮" },
  { label: "France", value: "FR", callingCode: "+33", emoji: "🇫🇷" },
  { label: "Gabon", value: "GA", callingCode: "+241", emoji: "🇬🇦" },
  { label: "Gambia", value: "GM", callingCode: "+220", emoji: "🇬🇲" },
  { label: "Georgia", value: "GE", callingCode: "+995", emoji: "🇬🇪" },
  { label: "Germany", value: "DE", callingCode: "+49", emoji: "🇩🇪" },
  { label: "Ghana", value: "GH", callingCode: "+233", emoji: "🇬🇭" },
  { label: "Greece", value: "GR", callingCode: "+30", emoji: "🇬🇷" },
  { label: "Grenada", value: "GD", callingCode: "+1-473", emoji: "🇬🇩" },
  { label: "Guatemala", value: "GT", callingCode: "+502", emoji: "🇬🇹" },
  { label: "Guinea", value: "GN", callingCode: "+224", emoji: "🇬🇳" },
  { label: "Guinea-Bissau", value: "GW", callingCode: "+245", emoji: "🇬🇼" },
  { label: "Guyana", value: "GY", callingCode: "+592", emoji: "🇬🇾" },
  { label: "Haiti", value: "HT", callingCode: "+509", emoji: "🇭🇹" },
  { label: "Honduras", value: "HN", callingCode: "+504", emoji: "🇭🇳" },
  { label: "Hungary", value: "HU", callingCode: "+36", emoji: "🇭🇺" },
  { label: "Iceland", value: "IS", callingCode: "+354", emoji: "🇮🇸" },
  { label: "India", value: "IN", callingCode: "+91", emoji: "🇮🇳" },
  { label: "Indonesia", value: "ID", callingCode: "+62", emoji: "🇮🇩" },
  { label: "Iran", value: "IR", callingCode: "+98", emoji: "🇮🇷" },
  { label: "Iraq", value: "IQ", callingCode: "+964", emoji: "🇮🇶" },
  { label: "Ireland", value: "IE", callingCode: "+353", emoji: "🇮🇪" },
  { label: "Israel", value: "IL", callingCode: "+972", emoji: "🇮🇱" },
  { label: "Italy", value: "IT", callingCode: "+39", emoji: "🇮🇹" },
  { label: "Jamaica", value: "JM", callingCode: "+1-876", emoji: "🇯🇲" },
  { label: "Japan", value: "JP", callingCode: "+81", emoji: "🇯🇵" },
  { label: "Jordan", value: "JO", callingCode: "+962", emoji: "🇯🇴" },
  { label: "Kazakhstan", value: "KZ", callingCode: "+7", emoji: "🇰🇿" },
  { label: "Kenya", value: "KE", callingCode: "+254", emoji: "🇰🇪" },
  { label: "Kiribati", value: "KI", callingCode: "+686", emoji: "🇰🇮" },
  { label: "Korea, North", value: "KP", callingCode: "+850", emoji: "🇰🇵" },
  { label: "Korea, South", value: "KR", callingCode: "+82", emoji: "🇰🇷" },
  { label: "Kosovo", value: "XK", callingCode: "+383", emoji: "🇽🇰" },
  { label: "Kuwait", value: "KW", callingCode: "+965", emoji: "🇰🇼" },
  { label: "Kyrgyzstan", value: "KG", callingCode: "+996", emoji: "🇰🇬" },
  { label: "Laos", value: "LA", callingCode: "+856", emoji: "🇱🇦" },
  { label: "Latvia", value: "LV", callingCode: "+371", emoji: "🇱🇻" },
  { label: "Lebanon", value: "LB", callingCode: "+961", emoji: "🇱🇧" },
  { label: "Lesotho", value: "LS", callingCode: "+266", emoji: "🇱🇸" },
  { label: "Liberia", value: "LR", callingCode: "+231", emoji: "🇱🇷" },
  { label: "Libya", value: "LY", callingCode: "+218", emoji: "🇱🇾" },
  { label: "Liechtenstein", value: "LI", callingCode: "+423", emoji: "🇱🇮" },
  { label: "Lithuania", value: "LT", callingCode: "+370", emoji: "🇱🇹" },
  { label: "Luxembourg", value: "LU", callingCode: "+352", emoji: "🇱🇺" },
  { label: "Madagascar", value: "MG", callingCode: "+261", emoji: "🇲🇬" },
  { label: "Malawi", value: "MW", callingCode: "+265", emoji: "🇲🇼" },
  { label: "Malaysia", value: "MY", callingCode: "+60", emoji: "🇲🇾" },
  { label: "Maldives", value: "MV", callingCode: "+960", emoji: "🇲🇻" },
  { label: "Mali", value: "ML", callingCode: "+223", emoji: "🇲🇱" },
  { label: "Malta", value: "MT", callingCode: "+356", emoji: "🇲🇹" },
  { label: "Marshall Islands", value: "MH", callingCode: "+692", emoji: "🇲🇭" },
  { label: "Mauritania", value: "MR", callingCode: "+222", emoji: "🇲🇷" },
  { label: "Mauritius", value: "MU", callingCode: "+230", emoji: "🇲🇺" },
  { label: "Mexico", value: "MX", callingCode: "+52", emoji: "🇲🇽" },
  { label: "Micronesia", value: "FM", callingCode: "+691", emoji: "🇫🇲" },
  { label: "Moldova", value: "MD", callingCode: "+373", emoji: "🇲🇩" },
  { label: "Monaco", value: "MC", callingCode: "+377", emoji: "🇲🇨" },
  { label: "Mongolia", value: "MN", callingCode: "+976", emoji: "🇲🇳" },
  { label: "Montenegro", value: "ME", callingCode: "+382", emoji: "🇲🇪" },
  { label: "Morocco", value: "MA", callingCode: "+212", emoji: "🇲🇦" },
  { label: "Mozambique", value: "MZ", callingCode: "+258", emoji: "🇲🇿" },
  { label: "Myanmar", value: "MM", callingCode: "+95", emoji: "🇲🇲" },
  { label: "Namibia", value: "NA", callingCode: "+264", emoji: "🇳🇦" },
  { label: "Nauru", value: "NR", callingCode: "+674", emoji: "🇳🇷" },
  { label: "Nepal", value: "NP", callingCode: "+977", emoji: "🇳🇵" },
  { label: "Netherlands", value: "NL", callingCode: "+31", emoji: "🇳🇱" },
  { label: "New Zealand", value: "NZ", callingCode: "+64", emoji: "🇳🇿" },
  { label: "Nicaragua", value: "NI", callingCode: "+505", emoji: "🇳🇮" },
  { label: "Niger", value: "NE", callingCode: "+227", emoji: "🇳🇪" },
  { label: "Nigeria", value: "NG", callingCode: "+234", emoji: "🇳🇬" },
  { label: "North Macedonia", value: "MK", callingCode: "+389", emoji: "🇲🇰" },
  { label: "Norway", value: "NO", callingCode: "+47", emoji: "🇳🇴" },
  { label: "Oman", value: "OM", callingCode: "+968", emoji: "🇴🇲" },
  { label: "Pakistan", value: "PK", callingCode: "+92", emoji: "🇵🇰" },
  { label: "Palau", value: "PW", callingCode: "+680", emoji: "🇵🇼" },
  { label: "Palestine", value: "PS", callingCode: "+970", emoji: "🇵🇸" },
  { label: "Panama", value: "PA", callingCode: "+507", emoji: "🇵🇦" },
  { label: "Papua New Guinea", value: "PG", callingCode: "+675", emoji: "🇵🇬" },
  { label: "Paraguay", value: "PY", callingCode: "+595", emoji: "🇵🇾" },
  { label: "Peru", value: "PE", callingCode: "+51", emoji: "🇵🇪" },
  { label: "Philippines", value: "PH", callingCode: "+63", emoji: "🇵🇭" },
  { label: "Poland", value: "PL", callingCode: "+48", emoji: "🇵🇱" },
  { label: "Portugal", value: "PT", callingCode: "+351", emoji: "🇵🇹" },
  { label: "Qatar", value: "QA", callingCode: "+974", emoji: "🇶🇦" },
  { label: "Romania", value: "RO", callingCode: "+40", emoji: "🇷🇴" },
  { label: "Russia", value: "RU", callingCode: "+7", emoji: "🇷🇺" },
  { label: "Rwanda", value: "RW", callingCode: "+250", emoji: "🇷🇼" },
  { label: "Saint Kitts and Nevis", value: "KN", callingCode: "+1-869", emoji: "🇰🇳" },
  { label: "Saint Lucia", value: "LC", callingCode: "+1-758", emoji: "🇱🇨" },
  { label: "Saint Vincent and the Grenadines", value: "VC", callingCode: "+1-784", emoji: "🇻🇨" },
  { label: "Samoa", value: "WS", callingCode: "+685", emoji: "🇼🇸" },
  { label: "San Marino", value: "SM", callingCode: "+378", emoji: "🇸🇲" },
  { label: "Sao Tome and Principe", value: "ST", callingCode: "+239", emoji: "🇹🇲" },
  { label: "Saudi Arabia", value: "SA", callingCode: "+966", emoji: "🇸🇦" },
  { label: "Senegal", value: "SN", callingCode: "+221", emoji: "🇸🇳" },
  { label: "Serbia", value: "RS", callingCode: "+381", emoji: "🇷🇸" },
  { label: "Seychelles", value: "SC", callingCode: "+248", emoji: "🇸🇨" },
  { label: "Sierra Leone", value: "SL", callingCode: "+232", emoji: "🇱🇸" },
  { label: "Singapore", value: "SG", callingCode: "+65", emoji: "🇸🇬" },
  { label: "Slovakia", value: "SK", callingCode: "+421", emoji: "🇸🇰" },
  { label: "Slovenia", value: "SI", callingCode: "+386", emoji: "🇸🇮" },
  { label: "Solomon Islands", value: "SB", callingCode: "+677", emoji: "🇸🇧" },
  { label: "Somalia", value: "SO", callingCode: "+252", emoji: "🇸🇴" },
  { label: "South Africa", value: "ZA", callingCode: "+27", emoji: "🇿🇦" },
  { label: "South Sudan", value: "SS", callingCode: "+211", emoji: "🇸🇸" },
  { label: "Spain", value: "ES", callingCode: "+34", emoji: "🇪🇸" },
  { label: "Sri Lanka", value: "LK", callingCode: "+94", emoji: "🇱🇰" },
  { label: "Sudan", value: "SD", callingCode: "+249", emoji: "🇸🇩" },
  { label: "Suriname", value: "SR", callingCode: "+597", emoji: "🇸🇷" },
  { label: "Sweden", value: "SE", callingCode: "+46", emoji: "🇸🇪" },
  { label: "Switzerland", value: "CH", callingCode: "+41", emoji: "🇨🇭" },
  { label: "Syria", value: "SY", callingCode: "+963", emoji: "🇸🇾" },
  { label: "Taiwan", value: "TW", callingCode: "+886", emoji: "🇹🇼" },
  { label: "Tajikistan", value: "TJ", callingCode: "+992", emoji: "🇹🇯" },
  { label: "Tanzania", value: "TZ", callingCode: "+255", emoji: "🇹🇿" },
  { label: "Thailand", value: "TH", callingCode: "+66", emoji: "🇹🇭" },
  { label: "Togo", value: "TG", callingCode: "+228", emoji: "🇹🇬" },
  { label: "Tonga", value: "TO", callingCode: "+676", emoji: "🇹🇴" },
  { label: "Trinidad and Tobago", value: "TT", callingCode: "+1-868", emoji: "🇹🇹" },
  { label: "Tunisia", value: "TN", callingCode: "+216", emoji: "🇹🇳" },
  { label: "Turkey", value: "TR", callingCode: "+90", emoji: "🇹🇷" },
  { label: "Turkmenistan", value: "TM", callingCode: "+993", emoji: "🇹🇲" },
  { label: "Tuvalu", value: "TV", callingCode: "+688", emoji: "🇹🇻" },
  { label: "Uganda", value: "UG", callingCode: "+256", emoji: "🇺🇬" },
  { label: "Ukraine", value: "UA", callingCode: "+380", emoji: "🇺🇦" },
  { label: "United Arab Emirates", value: "AE", callingCode: "+971", emoji: "🇦🇪" },
  { label: "United Kingdom", value: "GB", callingCode: "+44", emoji: "🇬🇧" },
  { label: "United States", value: "US", callingCode: "+1", emoji: "🇺🇸" },
  { label: "Uruguay", value: "UY", callingCode: "+598", emoji: "🇺🇾" },
  { label: "Uzbekistan", value: "UZ", callingCode: "+998", emoji: "🇺🇿" },
  { label: "Vanuatu", value: "VU", callingCode: "+678", emoji: "🇻🇺" },
  { label: "Vatican City", value: "VA", callingCode: "+379", emoji: "🇻🇦" },
  { label: "Venezuela", value: "VE", callingCode: "+58", emoji: "🇻🇪" },
  { label: "Vietnam", value: "VN", callingCode: "+84", emoji: "🇻🇳" },
  { label: "Yemen", value: "YE", callingCode: "+967", emoji: "🇾🇪" },
  { label: "Zambia", value: "ZM", callingCode: "+260", emoji: "🇿🇲" },
  { label: "Zimbabwe", value: "ZW", callingCode: "+263", emoji: "🇿🇼" }
]